# This is default and very simple configuration file for Yasb. 
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
watch_stylesheet: true
watch_config: true
debug: false
update_check: true # Enable automatic update check.
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 400
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "system"
    window_flags:
      always_on_top: false
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 4
      left: 4
      bottom: 0
      right: 4
    widgets:
      left:
      - "glazewm_workspaces"
      - "taskbar"
      # - "active_window"
      center:
      - "clock"
      right:
      - "glazewm_binding_mode"
      - "glazewm_tiling_direction"
      - "media"
      - "microphone"
      - "volume"
      - "notifications"
      - "systray"
widgets:
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\uf0d7"
      label_expanded: "\uf0da"
      label_position: "left" # Can be "left" or "right"
      icon_size: 18 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: true
      show_volume: false
      show_network: true
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist} - {title}"
      max_field_size:
        label: 18
        label_alt: 24
      show_thumbnail: true
      controls_only: false
      controls_left: true
      controls_hide: true
      hide_empty: true
      thumbnail_alpha: 100
      thumbnail_padding: 16
      thumbnail_corner_radius: 0
      thumbnail_edge_fade: true
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0a"
        pause: "\udb80\udfe4"
      media_menu:
        blur: false
        round_corners: false
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 4
        thumbnail_size: 100
        max_title_size: 80
        max_artist_size: 20
        show_source: true
      label_shadow:
        enabled: true
        color: "#000000"
        radius: 2
        offset: [ 1, 1 ]
      scrolling_label:
        enabled: true
        update_interval_ms: 50
        style: "left"  # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 1
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
  # active_window:
  #   type: "yasb.active_window.ActiveWindowWidget"
  #   options:
  #     label: "{win[title]}"
  #     label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
  #     label_no_window: ""
  #     label_icon: false
  #     label_icon_size: 14
  #     max_length: 60
  #     max_length_ellipsis: "..."
  #     monitor_exclusive: true
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 18
      tooltip: false
      show_only_visible: true
      strict_filtering: true
      monitor_exclusive: true
      animation:
        enabled: true
      preview:
        enabled: false
      title_label:
        enabled: true
        show: "focused"
        min_length: 0
        max_length: 60
      hide_empty: true
      callbacks:
        on_right: "context_menu"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b %I:%M %p}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      timezones: []
      calendar: 
        blur: false
        round_corners: false
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_calendar"
        on_right: "toggle_label"
  glazewm_binding_mode:
      type: "glazewm.binding_mode.GlazewmBindingModeWidget"
      options:
        label: '<span>{icon}</span>'
        label_alt: '<span>{icon}</span> {binding_mode}'
        icons:
          resize: "\uf047"
          pause: "\uf28c"
        binding_modes_to_cycle_through: [
          "none", # none handles if no binding mode is active
          "resize",
          "pause"
        ]
        callbacks:
          on_left: "next_binding_mode"
          on_middle: "toggle_label"
          on_right: "disable_binding_mode"

      # By default binding mode names are fetched from GlazeWM and "display_name" option takes priority over "name".
  glazewm_tiling_direction:
    type: "glazewm.tiling_direction.GlazewmTilingDirectionWidget"
    options:
      horizontal_label: "\udb81\udce1"
      vertical_label: "\udb81\udce2"
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      hide_empty_workspaces: true
      hide_if_offline: true
      active_populated_label: "\uebb4 {name}"
      active_empty_label: "\uebb5 {name}"
      # Want to make this work, but the styling in terms of border-radius and font-size seems to get messed up; probably because .label and .app-icons
      app_icons:
        enabled_active: false
        enabled_populated: true
        size: 10
        hide_duplicates: true


  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_volume_menu"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span> {level}"
      icons:
        normal: "\udb80\udf6c"
        muted: "\udb80\udf6d"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_mic_menu"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
